import type { Metadata } from 'next'
import { HeroOther } from '@/components/hero/heroOther'

export const metadata: Metadata = {
    metadataBase: new URL('https://localhost:8000'),
    title: 'LÍNEA PRO | CHOCOLATE MEXICANO',
    description: 'Generated by create next app',
    openGraph: {
        title: 'LÍNEA PRO | CHOCOLATE MEXICANO',
        description:
            'Chocoalte de uso profesional 100% mexicano cultivado en Tabasco',
        images: [
            {
                secureUrl:
                    'https://linea-pro.s3.us-east-2.amazonaws.com/lp-logos/lp-og.webp',
                url: 'https://linea-pro.s3.us-east-2.amazonaws.com/lp-logos/lp-og.webp',
                width: 1200,
                height: 630
            }
        ],
        url: 'http://localhost:8000',
        type: 'website'
    }
}

export default function NestedPageLayout({
    children
}: Readonly<{
    children: React.ReactNode
}>) {
    return (
        <>
            <HeroOther />
            {children}
        </>
    )
}
